# author 13
# qq-group 791509631
# email 2449207463@qq.com
# link https://github.com/newbee-ltd

# 服务器配置
server:
  port: 28079
  undertow:
    buffer-size: 1024
    direct-buffers: true
    threads:
      io: 16
      worker: 256
  servlet:
    session:
      tracking-modes: cookie

# 项目全局配置
project:
  name: newbee-mall-plus # 项目名称
  #  fileUploadPath: /opt/newbee-mall-plus/upload/  # 上传文件的默认url前缀，根据部署设置自行修改，linux下路径
  fileUploadPath: D:\\upload\\              # 上传文件的默认url前缀，根据部署设置自行修改，windows下路径
  orderUnpaidOverTime: 300 # 订单未支付超期时间，单位秒
  serverUrl: http://localhost:28079 # 服务器地址

# spring配置
spring:
  thymeleaf:
    cache: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  profiles:
    active: dev

# mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml    # mapper映射文件位置

# alipay 需要自行申请支付宝的沙箱账号、申请appID，并依次配置AppID、密钥、公钥，否则无法发起支付宝支付。
alipay:
  app-id: 2021000122615588
  rsa-private-key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDI2ccf/oE7h9WwH12gOO0G5G9CihBkzoS5LsZbJVTYodBxQed6qmj2SrcX/fw8NMKk8U+99pCvEBX/UeIOQWcpECKnbDIpo+gKf+UG7dFHcxhw5P38OeMlSFzJ2Wffy5vjmC7dVZG6yZocM2Pv6+ugjHsillU4sG1qq+ay9cirS2M2sC0ls6VXWoCtjh+P2gtfz21aJciEXoQxSBIzsaSm3oFxWYB6+7zLca8nW5Q2IMGsP8RoLgeOXY31Ve5qn+GPZ1b8HCQmfSwwjquDhnhKyRZFCs7FO+6DrXCP4dkNTSs7ZoqMEw5qXy2gqrJe5XJZUrD218YEU00i+udi9uH7AgMBAAECggEAcqvrxTeAPyXBeemegcCei0XWw+2hiHxkSHoNI7K/q2NPZ6pR57XtcVidCmSnIxSYYKWpenKQjnKnrHrqjmsG4+njbyUVyrJa48u7TeZvitSKisIixGOkbP/QginO5XYRDbMwZovZRQSfKSSqFSvj/mjWUJv2EgSgo7t7Xod3R1wiA85PynhD8Nd3obtgRumn5t/55vfRs3tw1nHs3HHAPpjHIks3oQgmyZIdA+7Ocjlcoqg+BRTkOmHiezpjRuo8p1iDMj9TjVadGakgeyAKTKJzeJ8wwT4MxptCLA+f9e1U++M4bI2nEcc63PD8PZr3T0EE6/Lc/bA5P/D+hlojaQKBgQD7LW5SV8UgmDCrLd6cNnc438J3m65kcgDddZVA4PsqCOxON5BpxQtJ13a9jJVM5hxXWs7jJDol/X7+pJIJLopnrhYEqCMQ7e/C/29CAP3APqZbWsKWE5+zU8SzLZTC9wFpBfZU9NLL2AIQNT6fEGnB2QOO/hlPjJnm2QfybKavlwKBgQDMtPwEKibu7I5YAUM4ifFb5M+QJL1ZxdNVyBx1v/HouEeye58wo7NTVsUS/gemQ1O2fOTkUk6wuiivV1rSg3DBcQWbPioeWRWE1Lc13b7ZMr0mKPgWbVLRhkspJauekhGxWxngk3eLYRuEok0mMVltHx5zt8MPlWcLjTkPzNqtPQKBgARzHJY22dYm/A28RUpNKLWIOUC3MFK1NlC2CYvZsHlhKRaFo3hMNlP7ji3zdJ2lIfFmOW4KsUEFCZ/nOHMTMP5/NgKlG+Hr5Sh2L/liXRxvv7C0nefctyKNJFnsP8toZsz+fwuoPqe/zuGMn+xfdRArEQYSeE5RdlSBmcNwq09HAoGAevhpv/K2aqaOJ82yXN94rvQ3v+ZiHPCasJhCiHWi02MIJu7eRTDBg9nHD06st7MQMbq7IXFUNhPOZu5576Xn8Tx82rIwSQTIyX+jA2fOwtkZCThpN8e6jYU312L6wooKuNj6JY9Qq9jM2BNLdxsEFmowN+F2+wCL40OVuKkd4B0CgYEA6hr+PQQsVqnusBS5rk3UJsigSgHl62z2KkGr5USXI7+t/l/4lZ9JUf5ZDyCXJNnn2Qmc8vmfAAgRpAfyd/HqWKJiVv5VYI1HB7GbmxHZQH9TbBMJxSDQtfHvNAzw33b9V/dpB+Zt5tzN8BbiOY7DHqHT1EPq1qsH7Enc5Kgvqpk=
  alipay-public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvSY0bBn22k9TSnFTFr0OTLv5zKOEAlztdB+jL1F0ohTmLpM+vRTH6eA8mHJ9DnPTTHdwk3xs+gLK35R/s1EAEELgO1zH6IknG1583glK5rB9nUgA/IXU/4fgVoV+je/d3Jd4teWaXGTAZ9dtnBb+nFcO4Tv1tq5GMQLCKSvW5Ub8zt+U5GkuFY6NeD2myF9pDs8zLK84xj7Nj/Ke67vXJsJRnvuPj5oRAhO0JMuVwKCj8/OwtgKvaEB8TVAl/2AKF4f+2UVfRuUG8EtyTjSQHV6B9F3vGGSmlLVIMGoK9lpiQcCusj1xVRFDBOwo8pe6qVHFqfScfOq3BulayCDtWQIDAQAB
  gateway: https://openapi.alipaydev.com/gateway.do
  charset: UTF-8
  format: json
  #  log-path: /opt/newbee-mall-plus/log
  log-path: D://newbee-mall-plus//log
  signtype: RSA2
